### ISSUE TITLE
Upstream?

### ISSUE THREAD

**Issue by Sevyls** [ktisha/snuggletex#1]
Dear ktisha,

i saw you added binom support to SnuggleTeX 1.2.2.

Do you know if and when your code is going to be merged into a new SnuggleTeX release? 

Thanks, sevyls

**Comment by ktisha** [comment]
Hi, 
unfortunately I have no idea. The latest commit in [snuggletex](http://sourceforge.net/p/snuggletex/code/HEAD/tree/) repository was 2013-08-15 

I can attach my custom jar here if you are interested.

**Comment by Sevyls** [comment]
ok, thanks that's not necessary.
I included a file of your code in my bachelor thesis project: https://github.com/Sevyls/latex-formulas-mobi-converter/ 

https://github.com/Sevyls/latex-formulas-mobi-converter/blob/master/latex2mobi-converter/src/main/java/at/ac/tuwien/ims/latex2mobiformulaconv/converter/mathml2html/snugglepkgs/BinomHandler.java

Thank you for your contributions to snuggletex!
